const icons: { [key: string]: string} = {
  "default": "https://cdn.simpleicons.org/headspace?viewbox=auto",
  "github": "https://cdn.simpleicons.org/github?viewbox=auto",
  "linkedin": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/LinkedIn_icon.svg/1200px-LinkedIn_icon.svg.png",
  "gmail": "https://cdn.simpleicons.org/gmail?viewbox=auto",
  "flask": "https://cdn.simpleicons.org/flask?viewbox=auto",
  "mysql": "https://cdn.simpleicons.org/mysql?viewbox=auto",
  "html": "https://cdn.simpleicons.org/html5?viewbox=auto",
  "javascript": "https://cdn.simpleicons.org/javascript?viewbox=auto",
  "postman": "https://cdn.simpleicons.org/postman?viewbox=auto",
  "githubactions": "https://cdn.simpleicons.org/githubactions?viewbox=auto",
  "css": "https://cdn.simpleicons.org/css3?viewbox=auto",
  "digitalocean": "https://cdn.simpleicons.org/digitalocean?viewbox=auto",
  "nginx": "https://cdn.simpleicons.org/nginx?viewbox=auto",
  "certbot": "https://cdn.simpleicons.org/certbot?viewbox=auto",
  "shell": "https://cdn.simpleicons.org/shell?viewbox=auto",
  "namecheap": "https://cdn.simpleicons.org/namecheap?viewbox=auto",
  "python": "https://cdn.simpleicons.org/python?viewbox=auto",
  "django": "https://cdn.simpleicons.org/django?viewbox=auto",
  "react": "https://cdn.simpleicons.org/react?viewbox=auto",
  "haproxy": "https://cdn.simpleicons.org/haproxy?viewbox=auto",
  "ubuntu": "https://cdn.simpleicons.org/ubuntu?viewbox=auto",
  "tailwindcss": "https://cdn.simpleicons.org/tailwindcss?viewbox=auto",
  "typescript": "https://cdn.simpleicons.org/typescript?viewbox=auto",
  "nextjs": "https://cdn.simpleicons.org/nextdotjs?viewbox=auto",
  "nodejs": "https://cdn.simpleicons.org/nodedotjs?viewbox=auto",
  "express": "https://cdn.simpleicons.org/express?viewbox=auto",
  "mongodb": "https://cdn.simpleicons.org/mongodb?viewbox=auto",
  "swagger": "https://cdn.simpleicons.org/swagger?viewbox=auto",
  "bootstrap": "https://cdn.simpleicons.org/bootstrap?viewbox=auto",
  "bash": "https://cdn.simpleicons.org/gnubash?viewbox=auto",
  "medium": "https://cdn.simpleicons.org/medium?viewbox=auto",
  "github link": "https://cdn.simpleicons.org/github/242424/ffffff?viewbox=auto",
  "linkedin link": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/LinkedIn_icon.svg/1200px-LinkedIn_icon.svg.png",
  "gmail link": "https://cdn.simpleicons.org/gmail/_/828282?viewbox=auto",
  "resume": "https://cdn.simpleicons.org/googledocs?viewbox=auto",
  "next": "https://cdn.simpleicons.org/nextdotjs?viewbox=auto",
  "drive": "https://cdn.simpleicons.org/googledrive?viewbox=auto",
  "c": "https://cdn.simpleicons.org/c?viewbox=auto",
  "git": "https://cdn.simpleicons.org/git?viewbox=auto",
  "linux": "https://cdn.simpleicons.org/linux?viewbox=auto",
  "fastapi": "https://cdn.simpleicons.org/fastapi?viewbox=auto",
  "trello": "https://cdn.simpleicons.org/trello?viewbox=auto",
  "notion": "https://cdn.simpleicons.org/notion?viewbox=auto",
  "sql": "https://cdn.simpleicons.org/mysql?viewbox=auto",
  "whatsapp": "https://cdn.simpleicons.org/whatsapp?viewbox=auto",
  "amazonwebservices": "https://cdn.simpleicons.org/amazonwebservices/_/ffffff?viewbox=auto",
  "calendly": "https://cdn.simpleicons.org/calendly?viewbox=auto",
  "redis": "https://cdn.simpleicons.org/redis?viewbox=auto",
  "netlify": "https://cdn.simpleicons.org/netlify?viewbox=auto",
  "vercel": "https://cdn.simpleicons.org/vercel?viewbox=auto",
  "postgresql": "https://cdn.simpleicons.org/postgresql?viewbox=auto",
  "ejs": "https://cdn.simpleicons.org/ejs?viewbox=auto",
  "heroku": "https://cdn.simpleicons.org/heroku?viewbox=auto",
}

export default icons;
