const projects = [
  {
    title: 'IWanBuy',
    description: 'A resturant web-application what allows users to order foods before pickup. Vendor management page also allows the resturant staff to manage available foods, create new foods, or view and approve orders for pickup.',
    technologies: ['React', 'Flask', 'MySQL', 'Bootstrap', 'Nginx', 'Bash', 'Postman', 'JavaScript', 'Python', 'Swagger'],
    url: 'https://www.iwanbuy.ng',
    repo: null,
    icon: null,
    image: '/iwanbuyImage.png',
    theme: 'orange',
  },
  {
    title: 'SCHub',
    description: 'SCHub is a webservice that transforms the manner in which institutions, like universities and colleges, handle data storage for students, teachers, departments and courses in a secure and user-friendly setting.',
    technologies: ["React", "Flask", "MySQL", "CSS", "Html", "DigitalOcean", "Nginx", "Bash", "Namecheap", "Python"],
    url: 'https://schub.jesulayomi.tech',
    repo: 'https://github.com/Jesulayomy/SCHub',
    icon: '/schubIcon.png',
    image: '/schubImage.png',
    theme: 'purple',
  },
  {
    title: 'NUESA FUNAAB',
    description: 'The improved website for the Nigerian Universities Engineering Students Association (NUESA), FUNAAB Chapter.',
    technologies: ["Nextjs", "Django", "MySQL", "TailwindCSS", "Html", "Bash", "Vercel", "Python", "JavaScript"],
    url: 'https://coleng-frontend.vercel.app',
    repo: 'https://github.com/Jesulayomy/Coleng-Frontend',
    icon: '/nuesaIcon.png',
    image: '/nuesaImage.png',
    theme: 'orange',
  },
  {
    title: 'GatherGo',
    description: 'GatherGo is a business in the transportation sector, which aims to provide a fine tuned ride sharing system, tailored to the community or environment in which it operates. (API Demo available)',
    technologies: ['Django', 'MySQL', 'Html', 'DigitalOcean', 'Postman', 'GithubActions', 'Nginx', 'Bash', 'NameCheap', 'Python'],
    url: 'https://gathergo.jesulayomi.tech/api/docs',
    repo: null,
    icon: '/gathergoIcon.png',
    image: '/gathergoImage.png',
    theme: 'green',
  },
  {
    title: 'Veda',
    description: 'Veda is a biometric attendance device, with a web API service that improves the strenous task of attendance taking in schools and institutions.',
    technologies: ['Flask', 'MySQL', 'Html', 'JavaScript', 'Postman', 'GithubActions', 'CSS', 'DigitalOcean', 'Nginx', 'Bash', 'NameCheap', 'Python'],
    url: 'https://veda.jesulayomi.tech',
    repo: 'https://github.com/Jesulayomy/Veda',
    icon: null,
    image: '/vedaImage.png',
    theme: 'blue',
  },
  {
    title: 'Let\'s Attend',
    description: 'This is the backend REST API of the LetsAttend project, which is an event manager that allows users to create, attend, and manage public and private events.',
    technologies: ['Flask', 'MySQL', 'Html', 'JavaScript', 'Postman', 'GithubActions', 'CSS', 'DigitalOcean', 'Nginx', 'Bash', 'NameCheap', 'Python'],
    url: 'https://lets-attend-api.jesulayomi.tech/apidocs/',
    repo: 'https://github.com/NUTEC-FUNAAB/Lets-attend-backend',
    icon: null,
    image: '/letsattendImage.png',
    theme: 'green',
  },
  {
    title: 'LibZ',
    description: 'LibZ is a user oriented public library that leverages the power of Google\'s Drive API to provide an application that allows users to upload, download and share books publicly over the web.',
    technologies: ['Flask', 'MySQL', 'Html', 'JavaScript', 'Postman', 'GithubActions', 'CSS', 'DigitalOcean', 'Nginx', 'Bash', 'NameCheap', 'Python'],
    url: null,
    repo: 'https://github.com/Jesulayomy/Libz',
    icon: '/libzIcon.png',
    image: '/libzImage.png',
    theme: 'yellow',
  },
  {
    title: 'LushLyrics Secured',
    description: 'LushLyrics Secured is a coursera project, which simulates project requirements, The django application was secured and issues were fixed.',
    technologies: ['Django', 'MySQL', 'Html', 'DigitalOcean', 'Postman', 'GithubActions', 'Nginx', 'Bash', 'NameCheap', 'Python'],
    url: 'https://lushlyrics.jesulayomi.tech/',
    repo: 'https://github.com/Jesulayomy/Lushlyrics-secure-django',
    icon: '/lushlyricsIcon.png',
    image: '/lushlyricsImage.png',
    theme: 'orange',
  },
  {
    title: 'Hbnb',
    description: 'HBNB is a clone of the AirBnB project done for Holberton School and ALX Africa. It uses an API framework to serve content for a rental service company.',
    technologies: ['Flask', 'MySQL', 'Html', 'JavaScript', 'Postman', 'GithubActions', 'CSS', 'DigitalOcean', 'Nginx', 'Bash', 'NameCheap', 'Python'],
    url: null,
    repo: 'https://github.com/Jesulayomy/AirBnB_clone_v4',
    icon: '/hbnbIcon.png',
    image: '/hbnbImage.png',
    theme: 'red',
  }
];

export default projects;
